#English
#Espanol
#Francais
#Portuguese
#Custom
LOCALE: "English"
#Enable this to have the trial vaults automatically reset themselves over time
AUTO UNLOCK: true
#Enable this to let players know when the vaults they used has all been auto reset.
UNLOCK NOTIFICATION: true
#Milliseconds: How long should players wait before they can reset a vault
#0 = no delay, allow players to spam keys
RESET_DELAY: 0
#If there is a delay on the vault, should it send a message to the player letting them know how much time left
PRINT_TIME_REMAINING: true